[project]
name = "book"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "ebooklib>=0.19",
    "fastapi[standard]>=0.116.2",
    "pydantic-settings>=2.11.0",
]
